; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:freenove_esp32_s3_wroom]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit INA219@^1.2.3
	adafruit/Adafruit NeoPixel@^1.15.5
	madhephaestus/ESP32Servo@^3.2.0
	# esp32async/AsyncTCP@^3.4.10
	# me-no-dev/ESPAsyncWebServer@^3.6.0
